### ISSUE TITLE
Shadow Disapearing

### ISSUE THREAD

**Issue by ForeverTPS** [BennyQBD/3DEngineCpp#11]
Shadow banding appears to be fixed but I still have this issue even with the most recent code. If you pan back while viewing the scene, the shadows begin to disappear. You can see the artifact line moving across where the shadows get removed although it is not visible in the images. I'm working on Windows, VS2013 and have a GTX770.

![capture1](https://cloud.githubusercontent.com/assets/1371608/3278500/af85a994-f3c2-11e3-9981-1d83c107bc86.PNG)
![capture2](https://cloud.githubusercontent.com/assets/1371608/3278502/b468af42-f3c2-11e3-9901-ab70ba9cae8d.PNG)
![capture3](https://cloud.githubusercontent.com/assets/1371608/3278504/b74e5c66-f3c2-11e3-9332-a9210297128d.PNG)

**Comment by pythoneer** [comment]
Yes, but thats no bug. This is intended to work as it is. If you had do lit ( and therefore shadowing ) a huge area you need a pretty damn big shadow map. to lower the cost of a massiv shadowmap, you only shadowing an area in a close distance to your camera and translate the shadowmap regarding to your camera position. you can adjust the factor of how far away from the camera the shadow disappears, but that is closely related to the resolution of the shadowmap regards the world distance units. eg. the more area you cover with your shadowmap the  lower gets the resolution of your shadowmap in like one by one meter.

**Comment by BennyQBD** [comment]
This is the effect we talked about in the generic directional light shadows video. Directional light shadows must have a finite range because the shadow map must have a finite resolution. Since directional lights cast light over an infinite area, then past some point shadows simply disappear, like you've shown here.

You can reduce this effect a lot using techniques like cascading shadow maps or light-space perspective shadow maps, but it will still occur to some extent. 

There is a way to "fix" this and have directional lights cast shadows throughout the entire view frustum: adjust the shadow area so it maps to the same area that the view frustum sees. Although this will get rid of the shadow disappearing effect, the shadow map will appear to have a very low resolution, since it's covering such a huge area. Overcoming that requires using the aforementioned more advanced techniques, like cascading shadow maps or light-space perspective shadow maps.
