### ISSUE TITLE
Explicit version number 120 not supported by GL3 forward compatible context

### ISSUE THREAD

**Issue by citruslee** [BennyQBD/3DEngineCpp#13]
Hi, it's me again with the same problem as on OSX. On M$ Windows 8.1 (MSVC 2013 Ultimate) I wasn't able to compile the program, just because those added lines, so I suggest to wrap it around like this

```
#ifdef __APPLE__ && ifdef __MACH__
    SDL_GL_SetAttribute( SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_CORE );
    SDL_GL_SetAttribute( SDL_GL_CONTEXT_MAJOR_VERSION, 3 );
    SDL_GL_SetAttribute( SDL_GL_CONTEXT_MINOR_VERSION, 2 );
 #endif
```

in window.cpp around line 25 and it should work out of the box

**Comment by citruslee** [comment]
you should check it on linux if it is needed or not (but I suppose not, hence you are working on linux). I would gladly test it on linux, but I am out of luck for now, my linux notebook blew up a month ago

**Comment by BennyQBD** [comment]
You're right that that does work, but it doesn't seem like the right solution because the engine shouldn't need to use the deprecated OpenGL features. Instead, I've changed the shader conversion code to covert to GLSL 150, since that matches OpenGL version 3.2

Let me know if there's any more issues; I really appreciate all this help!

**Comment by citruslee** [comment]
okay, no problem man :)
