### ISSUE TITLE
Mesh load failed!

### ISSUE THREAD

**Issue by ochos** [BennyQBD/3DEngineCpp#29]
Hi Benny, 
Thank you for your great tutorials, but I am having a issue with Mesh load failed as shown below. Do you have any idea why its happen? 
![screen shot 2015-01-21 at 14 44 40](https://cloud.githubusercontent.com/assets/8290228/5838025/2f2e0c60-a17c-11e4-99af-63558b6c793e.png)

I am using mac OS(Yosemite), Xcode6.1.1  and have installed SDL2, glew, assimp with brew and cmaked as you described. 
![screen shot 2015-01-21 at 14 49 33](https://cloud.githubusercontent.com/assets/8290228/5838110/c4c581b8-a17c-11e4-9f79-7e4504782531.png)
The models haven't been moved from the res folder.

Thank you in advance,
ochos

**Comment by zeyorama** [comment]
My first guess is your working directory is wrong.
Look, you are trying to access a folder starting from the location you are started the program. Lets imagine you are in your Home folder and starting the executable like ./Project/Program and your res folder is inside the Project folder. Now the Program tries to find the res folder not in your Project folder but in your Home folder instead, because your working directory is your Home folder.
Long speech no sense, your executable and your res folder needs to be in the same folder and your have to start your program in this folder with your working directory set to this folder.
If you are starting your program with an IDE, set your working directory inside the IDE to the folder, where your res folder is located.

Hope this helps and sorry for my bad english.
zeyorama

**Comment by ochos** [comment]
Dear zeyorama,

Thank you for your comment. It helps a lot and works properly! 
Sorry for my lateness.

Hide
