### ISSUE TITLE
Matrix Inverse implementation

### ISSUE THREAD

**Issue by zpl-zak** [BennyQBD/3DEngineCpp#38]
Does anybody have fixed matrix inverse function?

**Comment by zeyorama** [comment]
Not now, but after really short googling I found [this example implementation](https://chi3x10.wordpress.com/2008/05/28/calculate-matrix-inversion-in-c/).
Maybe this will help you.

Basically you calculate the determinant and checks if the determinant is not 0.0. Than you divide every component in your matrix by the determinant.

**Comment by zpl-zak** [comment]
Thank you, I'll look into it.

**Comment by vanAlem** [comment]
Fixed it:

... found the solution to the matrix Inverse function in math3d.h:

// This function doesn't appear to work!
  inline Matrix<T, D> Inverse() const
  {
   int i, j, k;
   Matrix<T, D> s;
   Matrix<T, D> t(*this);

This is because s is not initialized, set it to the identity (augmented part), then the Inverse function will work fine.
Matrix<T, D> s;
s.InitIdentity();

**Comment by zeyorama** [comment]
If it works properly, you could create a Pull Request, so Benny can merge it sometimes.
